import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Header from "../../components/header";
import Product from "./product";
import ProductDown from "./product";
import Button from "@material-ui/core/Button";
import React, { useState } from "react";
import ReactPaginate from "react-paginate";

import ArrowDownwardIcon from "@material-ui/icons/ArrowDownward";
import ArrowUpwardIcon from "@material-ui/icons/ArrowUpward";

export default function Products({ onAdd, setOpen, onSort }) {
 
  const [page, setPage] = useState(0);
  const pageSize = 3;  
  const productDisplayed = pageSize * page;
 
  const dispalyProduct = onSort
    ?.slice(productDisplayed, productDisplayed + pageSize)
    .map((product) => (
      <Product
        setOpen={setOpen}
        key={product.data.id}
        product={product}
        id={product.data.id}
        onAdd={onAdd}
      />
    ));

  const pageNumber = Math.ceil(onSort?.length / pageSize);
  const changePage = ({ selected }) => {
    setPage(selected);
  };
 
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          marginLeft: 8,
          marginBottom: 24,
          alignItems: "center",
         
        }}
      >
       
      
      </div>
     

      <div
        style={{
          display: "flex",
        }}
      >
        {onSort && onSort.length && dispalyProduct}{" "}
      </div>
      <div
        style={{
          display: "flex",
        }}
      >
        {onSort && onSort.length && dispalyProduct}{" "}
      </div>

      <ReactPaginate
        previousLabel={"Prev"}
        nextLabel={"Next"}
        pageCount={pageNumber}
        onPageChange={changePage}
        containerClassName={"boxcontainer"}
        previousLinkClassName={"prevbtn"}
        nextLinkClassName={"nextbtn"}
        disabledClassName={"disabledbtn"}
        activeClassName={"activelink"}
        disabledClassName={"disabled"}
      />
    </div>
  );
}
