import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Header from "../../components/header";
import useSWR from "swr";
import Product from "./product";
import ProductDown from "./product";
import Button from "@material-ui/core/Button";
import React, { useState } from "react";

export default function Products({onAdd, setOpen }) {
  const { data: products } = useSWR("./api/products");

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          display: "flex",
          justifyContent: "center",
          overflow: "hidden",
        }}
      >
        {products &&
          products.length &&
          products
          .splice(1,3)
            .map((product) => (
              <Product
               setOpen={setOpen}
                key={product.data.id}
                product={product}
                id={product.data.id}
                onAdd={onAdd}
              />
            ))}{" "}
      </div>
       <di
        style={{
          display: "flex",
          justifyContent: "center",
          overflow: "hidden",
        }}
      >
        {products &&
          products.length &&
          products
            .splice(1, 3)
            .map((product) => (
              <Product
              setOpen={setOpen}
              onAdd={onAdd}
                key={product.data.id}
                product={product}
                id={product.data.id}
              />
            ))}{" "}
      </di>
      <div 
        style={{ dispaly: "flex", justifyContent: "space-between", margin: 16 }}
      >
      
      </div>
    </div>
  );
}
